---
- ansible.builtin.import_tasks: install.yml

- name: configure users
  ansible.builtin.include_tasks: configure-groups.yml
  when: "users is defined and users not in ([], None, '', omit)"

- name: configure single node addons
  ansible.builtin.include_tasks: addons.yml
  when: not microk8s_enable_HA

- name: configure High Availability
  ansible.builtin.include_tasks: configure-HA.yml
  when: "microk8s_enable_HA"

- name: configure workers
  ansible.builtin.include_tasks: configure-WORKERS.yml
  when: "groups[microk8s_group_WORKERS] is defined and groups[microk8s_group_WORKERS]|length>0"
